source 'https://rubygems.org'
gem 'rails', '3.2.3'
gem 'sqlite3'
gem 'jquery-rails'
gem "haml", ">= 3.1.5"
gem "haml-rails", ">= 0.3.4"

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
end

gemspec :path => '../../'